swagger: '2.0'

## API Information
info:
  version: '0.0.3'
  title: "Simple öV transportation API"
  description: "A simple API to book öV tickets in Switzerland."
  contact:
    name: Team SVS Vertrieb
    email: andreas.schlapbach@sbb.ch
    url: http://transportationAPI.sbb.ch/
  license:
    name: SBB
    url: https://data.sbb.ch/page/licence/
host: localhost:10010 #transportationAPI.sbb.ch
basePath: /
schemes:
  - http # Nur am Anfang
  - https
consumes:
  - application/json
produces:
  - application/json
  - text/html  # Supported for response of annulllierungen
## Security
#securityDefinitions:
#  oauth:
#    type: oauth2
#    flow: implicit
#    authorizationUrl: https://xyz #To clarify
#    scopes:
#      basic: |
#       to read any and all data related to the B2P API
#security:
#  - oauth:
#    - basic

## Paths
paths:

  ### Fahrplan Part
  
  # ToDo: Define properly with Team VTP
  
  /standorte/{name}:
    x-swagger-router-controller: standorte
    get:
      description: "Hole Standorte Codes"
      operationId: getStandorte
      parameters:
        - name: name
          in: path
          description: "Name des Standortes"
          required: true
          type: string
      responses:
        200:
          description: "Eine Liste von Haltepunkte Codes"
          schema:
            type: array
            items:
              $ref: '#/definitions/standort'
        default:
          description: "unexpected error"

  # ToDo: Define properly with Team VTP

  /verbindungen/:
    x-swagger-router-controller: verbindungen
    post:
      description: "Hole Verbindungen"
      operationId: postVerbindungen
      parameters:
        - in: body
          name: verbindungsAnfrage
          description: "Anfrage für Verbindungen von A nach B."
          required: true
          schema:
            $ref: '#/definitions/verbindungsAnfrage'
      responses:
        200:
          description: "Eine Liste von Verbindungen"
          schema:
            type: array
            items:
              $ref: '#/definitions/verbindung'
        default:
          description: "unexpected error"

  ### Vertrieb Part
  
  /angebote/{recContext}:
    x-swagger-router-controller: angebote
    get: 
      description: "Hole Angebote für eine VerbindungsId (ReconstructionContext)"
      operationId: getAngebote
      parameters:
        - name: recContext
          in: path
          required: true
          type: string
      responses:
        200:
          description: "Eine Liste von Angeboten"
          schema:
            type: array
            items:
              $ref: '#/definitions/angebot'
        default:
          description: "unexpected error"
          
  /angebote/:
    x-swagger-router-controller: angebote
    post:
      description: "Hole Angebote"
      operationId: postAngebote
      parameters:
         - name: angebotsAnfrage
           in: body
           description: "Anfrage für Angebote für eine Verbindung oder Strecke."
           required: true
           schema:
              $ref: '#/definitions/angebotsAnfrage'
      responses:
        200:
          description: "Eine Liste von Angeboten"
          schema:
            type: array
            items:
              $ref: '#/definitions/angebot'
        default:
          description: "unexpected error"

  /vorabbuchungen/{angebotsId}:
    x-swagger-router-controller: vorabbuchungen
    get:
      description: "Vorabbuche das Angebot"
      operationId: getVorabbuchungen
      parameters:
        - name: angebotsId
          in: path
          description: "Id eines Angebotes"
          required: true
          type: string
      responses:
        200:
          description: "Vorabbuchung bestätigt"
          schema:
            $ref: '#/definitions/vorabbuchung'
        default:
          description: "unexpected error"

  /buchungen/{vorabbuchungsId}:
    x-swagger-router-controller: buchungen
    get:
      description: "Buche die Vorabbuchung"
      operationId: getBuchungen
      parameters:
        - name: vorabbuchungsId
          in: path
          description: "Id einer Vorabbuchung"
          required: true
          type: string
      responses:
        200:
          description: "Buchung bestätigt"
          schema:
            $ref: '#/definitions/buchung'
        default:
          description: "unexpected error"

  /billette/{buchungsId}:
    x-swagger-router-controller: billette
    get:
      description: "Hole das Billett"
      operationId: getBillette
      parameters:
        - name: buchungsId
          in: path
          description: "Id einer Buchung"
          required: true
          type: string
      responses:
        200:
          description: "Billett"
          schema:
            $ref: '#/definitions/billett'
        default:
          description: "unexpected error"


  ### SAV Part
  /annullierungen/{buchungsId}:
    x-swagger-router-controller: annullierungen
    get:
      description: "Annuliere die Buchung"
      operationId: getAnnullierungen
      parameters:
        - name: buchungsId
          in: path
          description: "Id einer Buchung"
          required: true
          type: string
      responses:
        200:
          description: "Buchung annulliert"
          schema:
            type: string
        default:
          description: "unexpected error"

## Definitions

definitions:
  # ToDo: Define properly with Team VTP
  standort:
    type: object
    required:
      - name
      - code
    properties:
      name:
        type: string
      code:
        type: string
  verbindungsAnfrage:
    type: object
    required:
      - vonCode
      - nachCode
      - datum
      - zeit
    properties:
      vonCode:
        description: "Abfahrtsort als UIC Code"
        type: integer
      viaCodes:
        type: array
        items:
          description: "Via Ort als UIC Code"
          type: integer
      nachCode:
        description: "Ankunftsort als UIC Code"
        type: integer
      datum:
        description: "Datum"
        type: string
        format: date
      zeit:
        description: "Zeit"
        type: string
        format: dateTime
  
  # ToDo: Define properly with Team VTP
  verbindung:
    type: object
    required:
      - verbindungsId
    properties:
      verbindungsId:
        description: "Id einer Verbindung (ReconstructionContext)"
        type: string
      zugNummer:
        description: "Zugnummer"
        type: string
      abfahrtsOrt:
        description: "Abfahrtsort"
        type: string    
      abfahrtsDatum:
        description: "Abfahrtsdatum"
        type: string
        format: date
      abfahrtsZeit:
        description: "Abfahrtszeit"
        type: string
        format: dateTime
      ankunftsOrt:
        description: "Ankunftsort"
        type: string
      ankunftsDatum:
        description: "Ankunftsdatum"
        type: string
        format: date
      ankunftsZeit:
        description: "Ankunftszeit"
        type: string
        format: dateTime
      links:
        type: array
        items:
          $ref: '#/definitions/link'

  strecke:
    type: object
    required:
      - von
      - nach
    properties:
      von:
        description: "Abfahrtsort"
        type: string
      nach:
        description: "Ankunftsort"
        type: string
      via:
        type: array
        items:
          type: string

  person:
    type: object
    required:
      - alter
    properties:
      alter:
        type: integer
      ermaessigung:
        type: string
        enum:
         - ga
         - halbtax
         
  angebotsAnfrage:
    type: object
    properties:
      strecke:
        $ref: '#/definitions/strecke'
      personen:
        type: array
        items:
          $ref: '#/definitions/person'
          
  angebot:
    type: object
    required:
      - angebotsId
      - beschreibung
      - preis
    properties:
      angebotsId:
        description: "Id eines Angebotes"
        type: string
      beschreibung:
        description: "Beschreibung des Angebotes"
        type: string
      preis:
        description: "Preis des Angebotes"
        type: integer
      links:
        type: array
        items:
          $ref: '#/definitions/link'

  vorabbuchung:
    type: object
    required:
     - vorabbuchungsId
    properties:
      vorabbuchungsId:
        description: "Id einer Vorabbbuchung"
        type: string
      links:
        type: array
        items:
          $ref: '#/definitions/link'

  buchung:
    type: object
    required:
     - buchungsId
    properties:
      buchungsId:
        description: "Id einer Buchung"
        type: string
      links:
        type: array
        items:
          $ref: '#/definitions/link'

  billett:
    type: object
    properties:
      typ:
        type: string
        enum:
        - pdf
        - screenTicket
      href:
        type: string

  ### REST level 3 support

  link:
    type: object
    required:
     - rel
     - href
    properties:
      rel:
        type: string
        description: "Aktion"
      href:
        type: string
        description: "URL zu Auslösung der Aktion"
